#GNU_INSTALL_ROOT := /usr/local/gcc-arm-none-eabi-4_9-2015q3
#GNU_VERSION := 4.9.3
#GNU_PREFIX := arm-none-eabi

GNU_INSTALL_ROOT := /home/dumpram/ARMCompilers/gcc-arm-none-eabi-5_4-2016q3
GNU_VERSION := 5.4.3
GNU_PREFIX := arm-none-eabi